### ISSUE TITLE
Sitronix CF1133 support

### ISSUE THREAD

**Issue by pnt325** [STMicroelectronics/stm32-sitronix#1]
Hi, 

I have project use Sitronix CF1133.

How can I port this driver to support on CF1133?

Thanks
Phat

**Comment by ALABSTM** [comment]
Hi @user-redans,

Thank you for your question. However, as indicated in the [CONTRIBUTING.md](https://github.com/STMicroelectronics/stm32-sitronix/blob/main/CONTRIBUTING.md#3-support-requests-and-questions), such support requests should be rather summitted to the [ST Community](https://community.st.com/t5/stm32-mcus-products/bd-p/stm32-mcu-products-forum). There you will hopefully find the answers you are looking for.

Please allow me to close this thread. Thank you for your comprehension.

With regards,
